name: EpiLAMA
channels:
  - conda-forge
dependencies:
  - python==3.12.9
  - pip==24.3.1
  - pip:
    - python-dotenv==1.0.1
    - flake8==7.1.1
    - openpyxl==3.1.5
    - isort==5.13.2
    - ipython==8.29.0
    - jupyterlab==4.2.6
    - matplotlib==3.9.2
    - clearml==1.16.5
    - clearml-agent==1.9.2
    - tqdm==4.67.1
    - seaborn==0.13.2
    - notebook==7.2.2
    - numpy==2.1.3
    - pandas==2.2.3
    - scikit-learn==1.5.2
    - torch==2.5.1
    - torchvision==0.20.1
    - torchaudio==2.5.1
    - transformers==4.46.3
    - levenshtein==0.26.1
    - biopython==1.84
    - beautifulsoup4==4.12.3
    - jax==0.6.1
    - esm==3.1.2
    - LightAutoML==0.4.1
