name: EpiLAMA-IM
channels:
  - conda-forge
dependencies:
  - python==3.10
  - pip==24.3.1
  - pip:
    - fairscale==0.4.10
    - ipdb==0.13.9
    - pandas==1.4.2
    - scikit-learn==1.0.2
    - scipy==1.8.0
    - seaborn==0.11.2
    - tensorboard==2.8.0
    - tqdm==4.64.0
    - tabulate==0.8.9
    - optuna==4.3.0
    - joblib==1.4.2
    - esm==3.1.2
    - lightautoml==0.4.1
    - transformers==4.46.3
    - torch==2.8.0
    - torch-tb-profiler==0.4.0
    - torchaudio
    - torchtext==0.18.0
    - torchvision==0.23.0
    - numpy==1.24.4
    - peptides
    - imbalanced-learn
    - matplotlib==3.6.3