models_dir: /mnt/nfs_protein/gavrilenko/vaccine-design/cytokine/models
esmc_model_name: esmc_600m
il2_model_path: IL-2 release_Homo sapiens (human)_smote_v1.joblib
il4_model_path: human_dfil4esmc.joblib
il10_model_path: human_dfil10esmc.joblib
ifng_model_path: IFNg release_Homo sapiens (human)_smote_v4.joblib
il2_mouse_model_path: mouse_base_IL-2 release.joblib
ifng_mouse_model_path: Mus musculus C57BL6_IFNg release_v4.joblib
il2_human_models:
  - CV-il2-esmc-None-Human-aap-fold1.joblib
  - CV-il2-esmc-None-Human-aap-fold2.joblib
  - CV-il2-esmc-None-Human-aap-fold3.joblib
  - CV-il2-esmc-None-Human-aap-fold4.joblib
  - CV-il2-esmc-None-Human-aap-fold5.joblib
il4_human_models:
  - il4_esmc_none_human_aac_f1.joblib
  - il4_esmc_none_human_aac_f2.joblib
  - il4_esmc_none_human_aac_f3.joblib
  - il4_esmc_none_human_aac_f4.joblib
  - il4_esmc_none_human_aac_f5.joblib
il10_human_models:
  - il10_esmc_smote_human_none_f1.joblib
  - il10_esmc_smote_human_none_f2.joblib
  - il10_esmc_smote_human_none_f3.joblib
  - il10_esmc_smote_human_none_f4.joblib
  - il10_esmc_smote_human_none_f5.joblib
ifng_human_models:
  - IFNg release_Homo sapiens (human)_None_CV_ifng_aac_esmc_fold0.joblib
  - IFNg release_Homo sapiens (human)_None_CV_ifng_aac_esmc_fold1.joblib
  - IFNg release_Homo sapiens (human)_None_CV_ifng_aac_esmc_fold2.joblib
  - IFNg release_Homo sapiens (human)_None_CV_ifng_aac_esmc_fold3.joblib
  - IFNg release_Homo sapiens (human)_None_CV_ifng_aac_esmc_fold4.joblib
aap_scores:
  AA: 0.5113322209840182
  AC: -0.09572275208848195
  AD: 0.11924141723341253
  AE: -0.07226382990698156
  AF: 0.29873805711879076
  AG: 0.49939533884153026
  AH: 0.1600433499525079
  AI: -0.07899191928081542
  AK: 0.03479478969429514
  AL: 0.7259751663934778
  AM: -0.38332206322383977
  AN: 0.4703644997893685
  AP: 0.04582297580032592
  AQ: -0.05658108109447845
  AR: 0.4262541593373375
  AS: 0.2703737146144541
  AT: -0.13959266477400376
  AV: -0.3834275384046533
  AW: -0.26747168153976
  AY: 0.045246638713233804
  CA: -0.3831464017236616
  CC: -6.03111531711023
  CD: -0.0005050272252891566
  CE: -0.3827955671517532
  CF: 0.8187932121503921
  CG: 0.0042649456273449295
  CH: -0.09564312742208125
  CI: -2.0302779805608746
  CK: -0.2009083231014119
  CL: -0.16022353104276488
  CM: -0.09461994125730801
  CN: -0.3577815132084075
  CP: -0.6417889792974389
  CQ: -2.386437549582626
  CR: -1.2981840247474314
  CS: 0.9250282350208417
  CT: -0.5652473265735006
  CV: -1.2732785176929229
  CW: -0.6046388738383545
  CY: -1.2840317156269456
  DA: -0.35804712462453947
  DC: -1.093086648515983
  DD: -0.6258277049766434
  DE: 0.037694362987071635
  DF: -1.0603553763382163
  DG: -0.394121117479305
  DH: -1.8764135054032296
  DI: 0.09338144851381765
  DK: -0.5010943753448769
  DL: -0.24657135105591915
  DM: -0.5646763948661471
  DN: -0.01575716870922458
  DP: -0.14225214656954002
  DQ: -0.2292179300532902
  DR: -0.8192714953473563
  DS: -0.2935362041740485
  DT: -0.22926962366728504
  DV: -0.5263901218235887
  DW: 1.686179157505821
  DY: 0.3091157210779848
  EA: 0.4778702364882008
  EC: -1.0751909090256146
  ED: 0.7143462201426746
  EE: 0.40403195770107203
  EF: -0.0386295001343295
  EG: -0.3989112472523576
  EH: 0.6763879369319388
  EI: 0.2756027023386685
  EK: 0.36832114745714417
  EL: 0.5101595881888209
  EM: 0.05827805079369074
  EN: 0.3412856694889144
  EP: -0.9424397999595523
  EQ: 0.26072751917030934
  ER: 0.18173587292975987
  ES: -0.2715852509394277
  ET: 0.21996919438492132
  EV: 0.1608603870915563
  EW: 1.337493949699548
  EY: 0.3502489023827397
  FA: 0.28966852397959686
  FC: -0.09561440664010075
  FD: -0.4208880285748011
  FE: -0.1910107739979059
  FF: 0.43460021446200575
  FG: -0.12968957245385376
  FH: 0.5962501836326699
  FI: 0.6922405561642913
  FK: 1.6761643483979642
  FL: 0.3017941940322409
  FM: 1.604133017402697
  FN: 0.5191260069942139
  FP: -0.8683648981997864
  FQ: 0.2606617645489138
  FR: -0.6295341476849307
  FS: 0.025535247216875796
  FT: -0.24988509329872827
  FV: 0.3946762015003981
  FW: 1.604133017402697
  FY: 0.0759793729184078
  GA: 0.205945392285496
  GC: -0.28669718805858735
  GD: -0.3559916259434908
  GE: -0.11448089784539096
  GF: -0.23884445702692655
  GG: -0.07580556863416994
  GH: -0.17910293344188233
  GI: -0.19894807206863127
  GK: -0.2209351699968128
  GL: 0.19521008136764334
  GM: -0.6186818646575374
  GN: -0.15133248603880736
  GP: 0.4561366940891311
  GQ: -0.09572939346675742
  GR: 0.27881103926756917
  GS: -0.3387143943785681
  GT: -0.18959704563464977
  GV: -0.6854672214418501
  GW: 0.16645611964194137
  GY: 0.501805221166432
  HA: -0.09577258491627903
  HC: 0.9952336824869105
  HD: 0.10472184720669554
  HE: 0.882662519331646
  HF: 1.4709464961199041
  HG: 0.21777972476140622
  HH: -0.5470035201411741
  HI: 1.6926734188172576
  HK: -0.5652473265735006
  HL: -0.09578021098599075
  HM: -0.38209584532063223
  HN: -0.8827201022312319
  HP: 0.30924894015019977
  HQ: -0.16022353104276488
  HR: 0.9642285680018602
  HS: -0.026799578558862603
  HT: -0.18262608868705588
  HV: -0.02168753258556656
  HW: 0.44256562550420775
  HY: -0.6339237579056001
  IA: -0.3779576008822428
  IC: 0.03765200601107105
  ID: -0.1726927746010701
  IE: 0.4505293603239452
  IF: -0.026811256138919402
  IG: 0.24057059009937204
  IH: -0.5652473265735006
  II: 0.4764959064856521
  IK: 0.6693582430356904
  IL: 0.3561120377206218
  IM: -1.0112636288392636
  IN: 0.2718028155647598
  IP: -0.17174668228144324
  IQ: -0.06404142375572344
  IR: -0.2257945333025454
  IS: -0.29639207903509274
  IT: -0.6188728510577908
  IV: 0.5797569320872067
  IW: -0.431359709512139
  IY: 0.8199135388413218
  KA: 0.26808049207621065
  KC: -0.5654379005894323
  KD: -0.17576951056239104
  KE: 0.4320679315715745
  KF: 0.5324821420969714
  KG: -0.5437196988833164
  KH: 0.5577147157478327
  KI: 0.009541523550009914
  KK: 0.23182073913731238
  KL: 0.28256133449818077
  KM: 0.2669133688238809
  KN: 0.2607604089934588
  KP: -0.5522782349116706
  KQ: -0.09578554995799718
  KR: -0.0800515265721604
  KS: 0.1425336787193982
  KT: 0.17605714879187698
  KV: -0.15520035197794105
  KW: 0.03765200601107105
  KY: 0.7399479554620645
  LA: 0.3270115701738352
  LC: -1.0751909090256146
  LD: -0.48434660787845485
  LE: 0.291425832573324
  LF: 0.004266293971908721
  LG: 0.04196226317921927
  LH: 0.2756027023386685
  LI: 0.10199168241096644
  LK: 0.1665253570970424
  LL: 0.48516730653769513
  LM: 0.42387053665311314
  LN: 0.356083409382184
  LP: 0.07512720987530194
  LQ: 0.3854173397052825
  LR: 0.6625564489875785
  LS: 0.44070009920475595
  LT: -0.23095462993155744
  LV: 0.2622084752571833
  LW: -0.1646649649818915
  LY: 0.18503158977160744
  MA: 0.1272677725503038
  MC: -0.6822924041019062
  MD: -0.31865802075489325
  ME: 0.1272378120650115
  MF: -0.19089569206472415
  MG: -0.3292349966282599
  MH: 0.9139830532924863
  MI: 0.22233785644245493
  MK: 0.24039911225545765
  ML: -0.5010197957650668
  MM: -0.0005050272252891566
  MN: -0.008794767214885096
  MP: 0.24014235555621982
  MQ: 0.7507757721314795
  MR: 0.10472184720669554
  MS: -1.0687532042276466
  MT: -0.3031885654535751
  MV: 0.1117256256913656
  MW: 0.08630660118055576
  MY: 0.30884962969827817
  NA: 0.3560404755949726
  NC: -0.09557422653383782
  ND: -0.8837548387163936
  NE: 0.3634107696627582
  NF: 0.01539899451526487
  NG: 0.07743165427199422
  NH: 0.5959805175070945
  NI: 0.6923407581090466
  NK: 0.015404405217049314
  NL: 0.5130923388168009
  NM: -0.5261816811753919
  NN: 0.3808963549392593
  NP: 0.12187032386310746
  NQ: 0.5577147157478327
  NR: -0.0957608015623315
  NS: 0.30954242990684827
  NT: -0.09577913247810585
  NV: 0.355997552268861
  NW: -0.38302938456317853
  NY: 0.47903914496437444
  PA: 0.20262915443235754
  PC: -0.09573515007399666
  PD: -0.7458229627006566
  PE: 0.5970306322445345
  PF: -0.3732824052908891
  PG: 0.2821702993329909
  PH: 0.22233785644245493
  PI: -0.17576951056239104
  PK: 0.3502489023827397
  PL: 0.7932264364815287
  PM: 0.3734374889893721
  PN: 0.2063329904207381
  PP: 0.1774215820147975
  PQ: -0.8237886869914637
  PR: 0.35301501212515485
  PS: -0.42419261444766604
  PT: -0.3470377156758027
  PV: -0.12244278124151108
  PW: -0.2494788817977454
  PY: -0.18272658504608166
  QA: 0.3202381336520473
  QC: -0.09521412063744884
  QD: -1.0881890035573105
  QE: -0.3368056137353048
  QF: -0.22915334595065975
  QG: -0.8408796017881927
  QH: -0.09568144866942707
  QI: -0.47290197549344537
  QK: 0.452581541260802
  QL: -0.012430931659184952
  QM: 0.30924894015019977
  QN: 0.6244196595948045
  QP: -0.9064639269209709
  QQ: -2.481523570524243
  QR: 0.37381227053238975
  QS: 0.3588103210453191
  QT: -0.5476013610812414
  QV: 0.06668026605953643
  QW: 0.30924894015019977
  QY: 0.5969705230657396
  RA: 0.41490494807978706
  RC: -1.6327124315606227
  RD: -0.8780911490809066
  RE: -0.051335217239036605
  RF: 0.8044588759125555
  RG: -0.2889525193336201
  RH: 0.17230155871294245
  RI: 0.4320679315715745
  RK: -0.1757991713557503
  RL: 0.07451719629849542
  RM: 1.0481998117284552
  RN: 0.07121318487494074
  RP: 0.24886860751059084
  RQ: 0.442872938397636
  RR: -0.383380653293761
  RS: -0.2097168433630461
  RT: -0.5880244991787538
  RV: 0.2871096484711765
  RW: 0.9323441642555107
  RY: 1.6926734188172576
  SA: 0.4290944050110589
  SC: -0.09571500497931093
  SD: -0.19751367298357403
  SE: 0.5280091942883801
  SF: 0.12120703308312648
  SG: -0.24236924334523147
  SH: 0.2063329904207381
  SI: 0.1978925673505936
  SK: -0.1182550757446328
  SL: 0.06762989697750457
  SM: 0.17230155871294245
  SN: -0.3700369293473553
  SP: 0.40475905947370616
  SQ: -0.9482809089404611
  SR: -0.7692713801268496
  SS: -0.06763290008838807
  ST: -0.4821370698349627
  SV: -0.14024130094018794
  SW: -0.05496546716392786
  SY: -0.39193344866102553
  TA: -0.834250987119354
  TC: -0.4208880285748011
  TD: -0.0005054326345553889
  TE: 0.14527222725669436
  TF: 0.7687779463868625
  TG: -0.4011192623441727
  TH: -0.0957446330552934
  TI: 0.20337554004523037
  TK: -0.39680358709739577
  TL: -0.03799069300949394
  TM: -0.21343965079495358
  TN: -0.09574858485241276
  TP: 0.24057059009937204
  TQ: -0.6634218624822291
  TR: -0.4800696137702069
  TS: -0.3386668082612581
  TT: -0.606440567716455
  TV: -0.49002205274509
  TW: -0.6214371515164926
  TY: 0.07849427945607769
  VA: 0.5867487069987712
  VC: -0.27792299416399086
  VD: -0.8532479688229871
  VE: 0.23437117370888602
  VF: 0.23545109431267883
  VG: 0.15547384065774159
  VH: 0.3252384396208003
  VI: -0.2857828025509103
  VK: 0.04727077101541595
  VL: -0.3419042563477096
  VM: -1.033137342284524
  VN: -0.37438140623925736
  VP: 0.8732659736184942
  VQ: -0.3033218137738154
  VR: 0.06543326276788651
  VS: -0.9026355849839727
  VT: -0.2271045779244711
  VV: -0.14090945102250407
  VW: -0.4518026964438332
  VY: 0.0018220920359964651
  WA: 0.3456259866874423
  WC: -2.0302779805608746
  WD: -0.27781592982915004
  WE: 0.5955316315228296
  WF: 0.7683747147922692
  WG: -0.23870018448480682
  WH: -0.01575716870922458
  WI: -0.6258277049766434
  WK: -0.7877595122812641
  WL: -0.5417564899394907
  WM: -0.2494788817977454
  WN: 0.9593087106977422
  WP: 0.9323441642555107
  WQ: -0.787519278533891
  WR: 0.3834622528584705
  WS: 1.2238170076811279
  WT: 0.7493673858984936
  WV: -0.147013742803409
  WW: -0.09461994125730801
  WY: 0.7493673858984936
  YA: 0.39352622563314316
  YC: 0.27861144683504896
  YD: 1.5104990095056794
  YE: -0.31873330339554434
  YF: 0.7683747147922692
  YG: -0.20492065766902198
  YH: 0.6455488976994946
  YI: -0.12653824512616643
  YK: -0.3468528090718858
  YL: 0.38173375173607643
  YM: -1.191357051406423
  YN: 0.1272378120650115
  YP: -0.1646649649818915
  YQ: 0.17230155871294245
  YR: 0.29178931945357933
  YS: -0.5944576528880414
  YT: 0.15537483075271555
  YV: 0.4329000916286955
  YW: 1.2818155081064628
  YY: -0.3407256827081817
